### ISSUE TITLE
Always check for proxies to detect possible network / upstream proxy changes

### ISSUE THREAD

**Issue by adrian-rt** [CoastalHacking/burp-pac#43]
Sometimes I have to switch between LAN and WIFI and the PAC only applies in the LAN, thus the plugin breaks. Can you please not cache the proxy for an website and make the check everytime? Or somehow fix this behaviour?

Thanks!

**Comment by jpasski** [comment]
@am06 as a workaround, does unloading and reloading the extension after you switch networks help?

**Comment by adrian-rt** [comment]
yeah, that's kinda of how it worked. didnt test properly, just once and had to move on.

**Comment by jpasski** [comment]
@am06 I cut a pre-release: https://github.com/CoastalHacking/burp-pac/releases/tag/lanswitch. Let me know if the attached JAR solves the issue you noted.
